function result = i_mymenu(strng)
% This is the machine-generated representation of a Handle Graphics object
% and its children.  Note that handle values may change when these objects
% are re-created. This may cause problems with any callbacks written to
% depend on the value of the handle at the time the object was saved.
% This problem is solved by saving the output as a FIG-file.
%
% To reopen this object, just type the name of the M-file at the MATLAB
% prompt. The M-file and its associated MAT-file must be on your path.
% 
% NOTE: certain newer features in MATLAB may not have been saved in this
% M-file due to limitations of this format, which has been superseded by
% FIG-files.  Figures which have been annotated using the plot editor tools
% are incompatible with the M-file/MAT-file format, and should be saved as
% FIG-files.
if nargin==0
   strng='Select option';
end;
%load i_mymenu
h0=i_figno('dialog');
if ishandle(h0)
   close(h0);
end;
h0 = figure(h0);
set(h0,'KeypressFcn','i_callb(''keypressed'')');
set(h0,'Units','points', ...
	'Color',[0.914 0.914 0.914], ...
	'Colormap',[], ...
	'MenuBar','none', ...
	'Name','State variables', ...
	'NumberTitle','off', ...
	'PaperPosition',[18 180 576 432], ...
	'PaperUnits','points', ...
	'Position',[200 170 160 240] ,...
	'Resize','off', ...
	'Tag','Fig1', ...
   'ToolBar','none',...
   'Visible','off',...
    'CreateFcn',@(h,evnt)movegui(gcbf, 'center'));

uicontrol('Parent',h0, ...
	'Units','points', ...
	'BackgroundColor',[0.914 0.914 0.914], ...
	'ListboxTop',0, ...
	'Position',[10 170 140 60], ...
	'String',strng, ...
	'Style','text', ...
	'Tag','StaticText1');
uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','set(gcf,''userdata'',1)', ...
	'ListboxTop',0, ...
	'Position',[10 160 140 25], ...
	'String','Run forward', ...
	'Tag','Pushbutton6');
uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','set(gcf,''userdata'',2)', ...
	'ListboxTop',0, ...
	'Position',[10 130 140 25], ...
	'String','Find nearest equilibrium', ...
	'Tag','Pushbutton5');
uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','set(gcf,''userdata'',3)', ...
	'ListboxTop',0, ...
	'Position',[10 100 140 25], ...
	'String','Set initial values only', ...
	'Tag','Pushbutton4');
uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','set(gcf,''userdata'',4)', ...
	'ListboxTop',0, ...
	'Position',[10 70 140 25], ...
	'String','Enable plot editing', ...
	'Tag','Pushbutton3');
uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','set(gcf,''userdata'',5)', ...
	'ListboxTop',0, ...
	'Position',[10 40 140 25], ...
	'String','Cancel', ...
	'Tag','Pushbutton2');
uicontrol('Parent',h0, ...
	'Units','points', ...
	'Callback','commands phasclick', ...
	'ListboxTop',0, ...
	'Position',[10 10 140 25], ...
	'String','Help', ...
	'Tag','Pushbutton1');
set(h0, 'Visible', 'on' );

%------------------------------------------------------------------------
% Wait for choice to be made (i.e UserData must be assigned)...
%------------------------------------------------------------------------
waitfor(h0,'userdata')
if ishandle(h0)
   result = get(h0,'userdata');
   delete(h0);
else
   result=5;
end;


