function selndx = i_parseldlg(tag, pars, Li, perc, critvals)
if nargin == 0
   tag = 'init';
   pars={};
   Li=[];
   perc=[0.05 0.25 0.5 0.75 0.95];
   critvals=zeros(size(perc));
end;
switch tag
case 'init'
   [Li1,ndx] = sort(Li); 
   ud.pars=pars;
   sortedpars=pars(ndx);
   f=find(perc>0.5);
   perc=perc(f);
   ud.Li=Li;
   ud.critvals=[-9999;critvals(f)'];
   ps=cell(1,length(perc)+1);
   ps{1}='all';
   for i=1:length(perc)
       ps{i+1}=sprintf('p<%g',1-perc(i));
   end;
   h0 = figure('Units','points', ...
      'MenuBar','none', ...
      'Name','Select parameters for dendrogram', ...
      'NumberTitle','off', ...
      'Color',[0.914 0.914 0.914], ...
      'PaperPosition',[18 180 576 432], ...
      'PaperUnits','points', ...
      'Position',[194.25 159.75 420 315], ...
      'Tag','parseldlg', ...
      'ToolBar','none');
   set(h0,'userdata',ud);
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[276.75 52.5 120.75 233.25], ...
      'String',sortedpars, ...
      'Style','listbox', ...
      'Tag','SelList', ...
      'Value', 1);
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'BackgroundColor',[0.914 0.914 0.914], ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[38.25 287.25 150 15], ...
      'String','Removed parameters', ...
      'Style','text', ...
      'Tag','StaticText1');
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'BackgroundColor',[1 1 1], ...
      'Position',[36 51 120.75 233.25], ...
      'String',' ', ...
      'Style','listbox', ...
      'Tag','UnselList', ...
      'Value', 1);
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'BackgroundColor',[0.914 0.914 0.914], ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[279 287.25 150 15], ...
      'String','Parameters for dendrogram', ...
      'Style','text', ...
      'Tag','StaticText1');
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'BackgroundColor',[0.914 0.914 0.914], ...
      'HorizontalAlignment','left', ...
      'ListboxTop',0, ...
      'Position',[188.25 230.25 70.5 15], ...
      'String','Select', ...
      'Style','text', ...
      'Tag','StaticText2');
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'Callback','i_parseldlg(''select'')', ...
      'ListboxTop',0, ...
      'Position',[187.5 169.5 59.25 22.5], ...
      'String','Select >>', ...
      'Tag','UnselectBtn');
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'Callback','i_parseldlg(''unselect'')', ...
      'ListboxTop',0, ...
      'Position',[188.25 137.25 55.5 22.5], ...
      'String','<< Remove', ...
      'Tag','SelectBtn');
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'BackgroundColor',[0.914 0.914 0.914], ...
      'Callback','i_parseldlg(''signif'')', ...
      'ListboxTop',0, ...
      'Position',[188.25 215.25 64.5 13.5], ...
      'String',ps, ...
      'Style','popupmenu', ...
      'Tag','SignifPopup', ...
      'Value', 1);
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'Callback','i_parseldlg(''OK'')', ...
      'ListboxTop',0, ...
      'Position',[331.5 13.5 64.5 22.5], ...
      'String','OK', ...
      'Tag','Pushbutton3');
   uicontrol('Parent',h0, ...
      'Units','points', ...
      'Callback','i_parseldlg(''Help'')', ...
      'ListboxTop',0, ...
      'Position',[249.75 13.5 64.5 22.5], ...
      'String','Help', ...
      'Tag','Pushbutton3');
   uiwait(h0);
   h = findobj(gcf, 'tag','SelList');
   selpars=get(h,'string');
   selndx=zeros(1,length(selpars));
   k=0;
   for j=1:length(selpars)
      for i=1:length(ud.pars)
         if strcmp(ud.pars{i},selpars{j})
            k=k+1;
            selndx(k)=i;
         end;
      end;
   end;
   selndx=sort(selndx(1:k));
   close;
case 'signif'
   h = findobj(gcbf, 'tag','SignifPopup');
   val=get(h, 'value');
   ud=get(gcbf,'userdata');
   ndx1=ud.critvals(val)>ud.Li;
   par1=ud.pars(ndx1);
   Li1=ud.Li(ndx1);
   par2=ud.pars(~ndx1);
   Li2=ud.Li(~ndx1);
   h = findobj(gcbf, 'tag','UnselList');
   [L,ndx] = sort(Li1); 
   set(h,'value',1);
   set(h,'string',par1(ndx));
   h = findobj(gcbf, 'tag','SelList');
   [L,ndx] = sort(Li2); 
   set(h,'value',1);
   set(h,'string',par2(ndx));
 case 'OK'
   uiresume;
 case 'Help'
   disp('help not yet implemented');
 case 'select'
   movefrom('UnselList','SelList');
 case 'unselect'
   movefrom('SelList','UnselList');
end;

function movefrom(listfrom, listto)
h = findobj(gcbf, 'tag',listfrom);
pars = get(h, 'string');
if ~isempty(pars)
   ipar = get(h, 'value');
   apar = pars{ipar};
   pars = {pars{1:ipar - 1} pars{ipar + 1:end}};
   if (ipar > length(pars)) && ~isempty(pars)
      set(h, 'value', length(pars));
   end;
   set(h, 'string',pars);
   h = findobj(gcbf, 'tag',listto);
   pars = get(h, 'string');
   if ischar(pars)
      pars = {apar};
   else
      pars = [pars {apar}]; 
      %do not change this to [pars {apar}] as that does not work
   end;
   set(h, 'string',pars);
end;
