function i_solverdlg(par1,par2)
global g_grind;
if nargin == 0
   par1 = 'init';
end;
switch par1
 case 'init'
      solverlist = solver('list');
      val = find(strcmp(solver('name'), solverlist));
   if isempty(g_grind.solver.opt.MaxStep)
      g_grind.solver.opt.MaxStep = 0.3;
   end;
   if isempty(g_grind.solver.opt.RelTol)
      g_grind.solver.opt.RelTol = 5e-5;
   end;
   if isempty(g_grind.solver.opt.AbsTol)
      g_grind.solver.opt.AbsTol = 1e-7;
   end;
   h1 = figure( ...
      'Units','characters',...
      'PaperUnits',get(0,'defaultfigurePaperUnits'),...
      'Color', [0.941 0.941 0.941], ...
      'IntegerHandle','off',...
      'InvertHardcopy',get(0,'defaultfigureInvertHardcopy'),...
      'MenuBar','none',...
      'Name','solver',...
      'NumberTitle','off',...
      'PaperPosition',get(0,'defaultfigurePaperPosition'),...
      'PaperSize',get(0,'defaultfigurePaperSize'),...
      'PaperType',get(0,'defaultfigurePaperType'),...
      'Position', [30.8 20 76.4 30.6923076923077], ...
      'Resize','off',...
      'HandleVisibility','callback',...
      'UserData', [], ...
      'Tag','figure1',...
      'Visible','on',...
    'CreateFcn',@(h,evnt)movegui(gcbf, 'center'));
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'Callback','i_solverdlg(''ok'')',...
      'FontUnits','pixels',...
      'FontSize', 10.6666666666667, ...
      'Position', [7.6 1.30769230769231 17.8 2.38461538461538], ...
      'String','OK',...
      'Tag','OKbutton' );
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'Callback','i_solverdlg(''cancel'')',...
      'FontUnits','pixels',...
      'FontSize', 10.6666666666667, ...
      'Position', [29.8 1.30769230769231 17.8 2.38461538461538], ...
      'String','Cancel',...
      'Tag','Cancelbutton' );
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'Callback','i_solverdlg(''help'')',...
      'FontUnits','pixels',...
      'FontSize', 10.6666666666667, ...
      'Position', [52 1.30769230769231 17.8 2.38461538461538], ...
      'String','Help',...
      'Tag','Helpbutton');
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontSize', 10.6666666666667, ...
      'HorizontalAlignment','left',...
      'Position', [9.8 25 22 1.76923076923077], ...
      'String','Solver',...
      'Style','text',...
      'Tag','text1' );
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'Callback','i_solverdlg(''solverchanged'')', ...
      'BackgroundColor', [1 1 1], ...
      'FontSize', 10.6666666666667, ...
      'Position', [32.2 25 27.4 1.69230769230769], ...
      'String', solverlist, ...
      'Style','popupmenu',...
      'Value', val, ...
      'Tag','SolverPopup' );
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontSize', 10.6666666666667, ...
      'HorizontalAlignment','left',...
      'Position', [9.8 21.7692307692308 22.2 1.30769230769231], ...
      'String','Absolute tolerance',...
      'Style','text',...
      'Tag','AbsToltext' );
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor', [1 1 1], ...
      'FontSize', 10.6666666666667, ...
      'HorizontalAlignment','left',...
      'Position', [32.2 21.6923076923077 27.6 1.76923076923077], ...
      'String', num2str(g_grind.solver.opt.AbsTol), ...
      'Style','edit',...
      'Tag','AbsTolEdit' );
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor', [1 1 1], ...
      'FontSize', 10.6666666666667, ...
      'HorizontalAlignment','left',...
      'Position', [32.2 21.6923076923077 27.6 1.76923076923077], ...
      'String', num2str(g_grind.solver.opt.MaxStep), ...
      'Style','edit',...
      'Tag','MaxStepEdit',...
      'Visible','off');
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor', [1 1 1], ...
      'FontSize', 10.6666666666667, ...
      'HorizontalAlignment','left',...
      'Position', [32.2 21.6923076923077 27.6 1.76923076923077], ...
      'String', num2str(g_grind.solver.iters), ...
      'Style','edit',...
      'Tag','ItersEdit',...
      'Visible','off');
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontSize', 10.6666666666667, ...
      'HorizontalAlignment','left',...
      'Position', [9.8 18.0769230769231 22 1.76923076923077], ...
      'String','Relative Tolerance',...
      'Style','text',...
      'Tag','RelToltext' );
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontSize', 10.6666666666667, ...
      'Position', [9.8 14.3076923076923 35.2 1.84615384615385], ...
      'String','Backwards',...
      'Style','checkbox',...
      'Value', g_grind.solver.backwards, ...
      'Tag','Backwcheck' );
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'BackgroundColor', [1 1 1], ...
      'FontSize', 10.6666666666667, ...
      'HorizontalAlignment','left',...
      'Position', [32.2 18.3846153846154 27.6 1.76923076923077], ...
      'String', num2str(g_grind.solver.opt.RelTol), ...
      'Style','edit',...
      'Tag','RelTolEdit' );
   
   uicontrol( ...
      'Parent', h1, ...
      'Units','characters',...
      'FontUnits','pixels',...
      'FontSize', 10.6666666666667, ...
      'Position', [9.8 10.5384615384615 35.2 1.84615384615385], ...
      'String','Add mode',...
      'Value', g_grind.solver.addmode, ...
      'Style','checkbox',...
      'Tag','AddModecheck' );
     if g_grind.solver.isdiffer
      h=findobj(h1,'Tag','AbsToltext');
      set(h,'String','Iterations');
      h=findobj(h1,'Tag','AbsTolEdit');
      set(h,'visible','off');
      h=findobj(h1,'Tag','ItersEdit');
      set(h,'visible','on');
      h=findobj(h1,'Tag','MaxStepEdit');
      set(h,'visible','off');
      h=findobj(h1,'Tag','RelToltext');
      set(h,'visible','off');
      h=findobj(h1,'Tag','RelTolEdit');
      set(h,'visible','off');
     end
     i_solverdlg('solverchanged', h1);
     uiwait(h1);
     close(h1);
 case 'solverchanged'
   if nargin==2
      h1=par2;
   else
      h1=gcbf;
   end;
   h=findobj(h1,'Tag','SolverPopup');
   solverlist = get(h, 'String');
   val = get(h, 'Value');
   asolver = solverlist{val};
   if find(strcmp(asolver,{'euler','rk4'}))
      h=findobj(h1,'Tag','AbsToltext');
      set(h,'String','Step size');
      h=findobj(h1,'Tag','AbsTolEdit');
      set(h,'visible','off');
      h=findobj(h1,'Tag','ItersEdit');
      set(h,'visible','off');
      h=findobj(h1,'Tag','MaxStepEdit');
      set(h,'visible','on');
      h=findobj(h1,'Tag','RelToltext');
      set(h,'visible','off');
      h=findobj(h1,'Tag','RelTolEdit');
      set(h,'visible','off');
   elseif ~g_grind.solver.isdiffer
      h=findobj(h1,'Tag','AbsToltext');
      set(h,'String','Absolute Tolerance');
      h=findobj(h1,'Tag','AbsTolEdit');
      set(h,'visible','on');
      h=findobj(h1,'Tag','ItersEdit');
      set(h,'visible','off');
      h=findobj(h1,'Tag','MaxStepEdit');
      set(h,'visible','off');
      h=findobj(h1,'Tag','RelToltext');
      set(h,'visible','on');
      h=findobj(h1,'Tag','RelTolEdit');
      set(h,'visible','on');
   end;
 case 'ok'
   if ~(g_grind.solver.haslag || g_grind.solver.isdiffer)
     h=findobj(gcbf,'Tag','SolverPopup' );
     solverlist = get(h, 'String');
     aval = get(h, 'Value');
     solver(solverlist{aval});
   end;
   h=findobj(gcbf, 'Tag','AbsTolEdit' );
   g_grind.solver.opt.AbsTol = str2double(get(h, 'String'));
   h=findobj(gcbf, 'Tag','MaxStepEdit');
   g_grind.solver.opt.MaxStep = str2double(get(h, 'String'));
   h=findobj(gcbf, 'Tag','ItersEdit');
   g_grind.solver.iter = str2double(get(h, 'String'));
   h=findobj(gcbf, 'Tag','Backwcheck' );
   g_grind.solver.backwards = get(h, 'Value');
   h=findobj(gcbf, 'Tag','RelTolEdit' );
   g_grind.solver.opt.RelTol = str2double(get(h, 'String'));
   h=findobj(gcbf, 'Tag','AddModecheck' );
   g_grind.solver.addmode = get(h, 'Value');
  uiresume(gcbf);
 case 'cancel'
   uiresume(gcbf);
 case 'help'
   commands('solver');
end

